### ISSUE TITLE
Interleaved image file handled incorrectly

### ISSUE THREAD

**Issue by jduerstock** [jmechnich/wteledsk#1]
When unpacking this file:

http://www.retroarchive.org/maslin/disks/kpro/copwrdos.td0

I get the following errors:

Warning skipping  1 sectors (2 through 2) on track 0
Warning skipping  1 sectors (4 through 4) on track 0
Warning skipping  1 sectors (6 through 6) on track 0
Warning skipping  1 sectors (8 through 8) on track 0
Warning repeating sector  2 on track 0
Warning repeating sector  4 on track 0
Warning repeating sector  6 on track 0
Warning repeating sector  8 on track 0
(repeats for side 1 and tracks 1-39)

I believe this is because the sectors in the .td0 file are interleaved.  Is there an easy way to fix this?

**Comment by jmechnich** [comment]
Hi there,

honestly, I don't know. Maybe it is possible to try the original program in e.g. dosbox ?

Regards,
Jörg

**Comment by jduerstock** [comment]
Would it be possible to buffer a track at a time, and then flag missing/duplicate sectors right before moving to the next track?

**Comment by jmechnich** [comment]
Sorry for the late reply (and the bad news): I am happy to accept pull requests in case you are interested in updating the code but I have currently no time or interest in looking at this myself. This repository was created mainly for documenting and preserving code that was not written by me but very useful a couple of years ago.
