### ISSUE TITLE
Can't decompress td0 images

### ISSUE THREAD

**Issue by al20878** [jmechnich/wteledsk#2]
Hi,

First off,  Thank you for the effort to provide the teledisk reading program to the community!

Unfortunately, I could not produce any usable images out of the compressed .td0 files in here (fortunately, there are also decompressed images stored along):
http://www.ibiblio.org/pub/academic/computer-science/history/pdp-11/pro/

I was doing this under the freshest Cygwin with one of the latest gcc -- building the executable was no problem aside from a couple compiler warnings.
```
$ uname -a
CYGWIN_NT-6.1 XXXX 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin

$ gcc --version
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Looking around, I found this very good description of the td format that you might find quite useful:
http://dunfield.classiccmp.org/img47321/td0notes.txt
Because I noticed that your description of the format differs (in parts that pertain to sector decompression) quite a bit.

The .td0 files, which I was playing with, do, however, check out well with the old TDCHECK executables (run in DosBox) that are collected here:
http://dunfield.classiccmp.org/img47321/teledisk.htm

Attaching a patch to get rid of the compiler warnings mentioned above:
```
$ git diff wteledsk.c
diff --git a/src/wteledsk.c b/src/wteledsk.c
index 227b984..f02e5e7 100644
--- a/src/wteledsk.c
+++ b/src/wteledsk.c
@@ -47,7 +47,9 @@
 #include <io.h>         // for lseek
 #else
 #include <unistd.h>
+#ifndef O_BINARY^M
 #define O_BINARY 0      // not defined for Linux gcc
+#endif^M
 #define strnicmp strncasecmp
 #endif
 #include <sys/types.h>
@@ -180,7 +182,7 @@ struct rep_rec {
 #define BLKSZMSK 0x7 // low order 3 bits, only expect to use 2 of them


-int block_size(ctl)
+int block_size(unsigned ctl)^M
 {
     int j,sz=128;
     j = ctl & BLKSZMSK;
@@ -706,7 +708,7 @@ int main(int argc,char *argv[])

     }
     else if(rd >= 0x10)
-         printf("\ninvalid id %2.2s",block);
+         printf("\ninvalid id %2.2s",(char*) fhead);^M
     else
          printf("\nread error, header not long enough");
     adr = sizeof(struct file_head); // set track data to start after fhead
```

**Comment by jmechnich** [comment]
Hi there,

sorry for the very late reply and thanks for the patch. I have finally added those changes.

With respect to your comments regarding the TD format: this repository is mostly for preservation purposes of the code that was useful to me a couple of years ago but I have not worked with teledisk images in a long while. It is unlikely that I will make major changes in the future (except the merging of pull requests by other people).
